// packages/wc/src/dotlottie-worker-wc.ts
/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Config } from '@lottiefiles/dotlottie-web';
import { DotLottieWorker } from '@lottiefiles/dotlottie-web';
import { customElement } from 'lit/decorators.js';

import { BaseDotLottieWC } from './base-dotlottie-wc';

@customElement('dotlottie-worker-wc')
export class DotLottieWorkerWC extends BaseDotLottieWC<DotLottieWorker> {
  protected override _createDotLottieInstance(config: Config & { workerId?: string }): DotLottieWorker {
    return new DotLottieWorker(config);
  }
}

// packages/react/src/dotlottie-worker.tsx
import type { Config } from '@lottiefiles/dotlottie-web';
import { DotLottieWorker } from '@lottiefiles/dotlottie-web';

import { BaseDotLottieReact } from './base-dotlottie-react';
import type { BaseDotLottieProps } from './base-dotlottie-react';

export type DotLottieWorkerReactProps = Omit<BaseDotLottieProps<DotLottieWorker>, 'createDotLottie'>;

const createDotLottieWorker = (config: Config & { workerId?: string }): DotLottieWorker => new DotLottieWorker(config);

export const DotLottieWorkerReact: React.FC<DotLottieWorkerReactProps> = (props) => {
  return <BaseDotLottieReact {...props} createDotLottie={createDotLottieWorker} />;
};
