// packages/solid/src/use-dotlottie.tsx
import { type Config, DotLottie } from '@lottiefiles/dotlottie-web';
import debounce from 'debounce';
import type { Accessor, ComponentProps, JSX } from 'solid-js';
import { on, createEffect, createMemo, createSignal, onCleanup } from 'solid-js';
import { isServer } from 'solid-js/web';

interface DotLottieComponentProps {
  setCanvasRef: (el: HTMLCanvasElement) => void;
  setContainerRef: (el: HTMLDivElement) => void;
}

function DotLottieComponent({
  children,
  class: className,
  setCanvasRef,
  setContainerRef,
  style,
  ...rest
}: DotLottieComponentProps & ComponentProps<'canvas'>): JSX.Element {
  const containerStyle = {
    width: '100%',
    height: '100%',
    ...(style as JSX.CSSProperties),
  };

  return (
    <div ref={setContainerRef} class={className} {...{ style: containerStyle }}>
      <canvas
        ref={setCanvasRef}
        style={{
          width: '100%',
          height: '100%',
        }}
        {...rest}
      >
        {children}
      </canvas>
    </div>
  );
}

export type DotLottieConfig = Omit<Config, 'canvas'> &
  Partial<{
    animationId?: string;
    autoResizeCanvas: boolean;
    playOnHover: boolean;
    themeData?: string;
    themeId?: string;
  }>;

export interface UseDotLottieReturn {
  DotLottieComponent: (props: ComponentProps<'canvas'>) => JSX.Element;
  canvas: HTMLCanvasElement | null;
  container: HTMLDivElement | null;
  dotLottie: Accessor<DotLottie | null>;
  setCanvasRef: (el: HTMLCanvasElement) => void;
  setContainerRef: (el: HTMLDivElement) => void;
}

export const useDotLottie = (config: DotLottieConfig): UseDotLottieReturn => {
  const [dotLottie, setDotLottie] = createSignal<DotLottie | null>(null);

  let canvasRef: HTMLCanvasElement | null = null;
  let containerRef: HTMLDivElement | null = null;

  const hoverHandler = (event: MouseEvent): void => {
    const dotLottieInstance = dotLottie();

    if (!config.playOnHover || !dotLottieInstance) return;

    if (event.type === 'mouseenter') {
      dotLottieInstance.play();
    } else if (event.type === 'mouseleave') {
      dotLottieInstance.pause();
    }
  };

  const intersectionObserver = createMemo(() => {
    if (isServer) return null;

    const observerCallback = debounce((entries: IntersectionObserverEntry[]) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          dotLottie()?.unfreeze();
        } else {
          dotLottie()?.freeze();
        }
      });
    }, 150);

    return new IntersectionObserver(observerCallback, {
      threshold: 0,
    });
  });

  const resizeObserver = createMemo(() => {
    if (isServer) return null;

    const observerCallback = debounce(() => {
      if (config.autoResizeCanvas) {
        dotLottie()?.resize();
      }
    }, 150);

    return new ResizeObserver(observerCallback);
  });

  const setCanvasRef = (canvas: HTMLCanvasElement | null): void => {
    if (canvas) {
      const dotLottieInstance = new DotLottie({
        ...config,
        canvas,
      });

      setDotLottie(dotLottieInstance);

      // check if canvas is initially in view
      const initialEntry = canvas.getBoundingClientRect();

      if (
        initialEntry.top >= 0 &&
        initialEntry.left >= 0 &&
        initialEntry.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
        initialEntry.right <= (window.innerWidth || document.documentElement.clientWidth)
      ) {
        dotLottie()?.unfreeze();
      } else {
        dotLottie()?.freeze();
      }

      intersectionObserver()?.observe(canvas);
      if (config.autoResizeCanvas) {
        resizeObserver()?.observe(canvas);
      }

      canvas.addEventListener('mouseenter', hoverHandler);
      canvas.addEventListener('mouseleave', hoverHandler);
    } else {
      dotLottie()?.destroy();
      intersectionObserver()?.disconnect();
      resizeObserver()?.disconnect();
    }

    canvasRef = canvas;
  };

  const setContainerRef = (el: HTMLDivElement | null): void => {
    containerRef = el;
  };

  const Component = (props: ComponentProps<'canvas'>): JSX.Element => {
    return <DotLottieComponent setContainerRef={setContainerRef} setCanvasRef={setCanvasRef} {...props} />;
  };

  onCleanup(() => {
    dotLottie()?.destroy();
    setDotLottie(null);
    resizeObserver()?.disconnect();
    intersectionObserver()?.disconnect();
    if (canvasRef) {
      canvasRef.removeEventListener('mouseenter', hoverHandler);
      canvasRef.removeEventListener('mouseleave', hoverHandler);
    }
  });

  // Reactivities
  // speed
  createEffect(() => {
    const dotLottieInstance = dotLottie();

    if (!dotLottieInstance) return;

    if (typeof config.speed === 'number' && config.speed !== dotLottieInstance.speed && dotLottieInstance.isLoaded) {
      dotLottieInstance.setSpeed(config.speed);
    }
  });
  // mode
  createEffect(() => {
    const dotLottieInstance = dotLottie();

    if (!dotLottieInstance) return;

    if (typeof config.mode === 'string' && config.mode !== dotLottieInstance.mode && dotLottieInstance.isLoaded) {
      dotLottieInstance.setMode(config.mode);
    }
  });
  // loop
  createEffect(() => {
    const dotLottieInstance = dotLottie();

    if (!dotLottieInstance) return;

    if (typeof config.loop === 'boolean' && config.loop !== dotLottieInstance.loop && dotLottieInstance.isLoaded) {
      dotLottieInstance.setLoop(config.loop);
    }
  });
  // useFrameInterpolation
  createEffect(() => {
    const dotLottieInstance = dotLottie();

    if (!dotLottieInstance) return;

    if (
      typeof config.useFrameInterpolation === 'boolean' &&
      config.useFrameInterpolation !== dotLottieInstance.useFrameInterpolation &&
      dotLottieInstance.isLoaded
    ) {
      dotLottieInstance.setUseFrameInterpolation(config.useFrameInterpolation);
    }
  });
  // segment
  createEffect(() => {
    const dotLottieInstance = dotLottie();

    if (!dotLottieInstance) return;

    if (typeof config.segment === 'object' && Array.isArray(config.segment) && dotLottieInstance.isLoaded) {
      const startFrame = config.segment[0];
      const endFrame = config.segment[1];

      dotLottieInstance.setSegment(startFrame, endFrame);
    }
  });
  // background color
  createEffect(() => {
    const dotLottieInstance = dotLottie();

    if (!dotLottieInstance) return;

    if (
      typeof config.backgroundColor === 'string' &&
      config.backgroundColor !== dotLottieInstance.backgroundColor &&
      dotLottieInstance.isLoaded
    ) {
      dotLottieInstance.setBackgroundColor(config.backgroundColor);
    }
  });
  // render config
  createEffect(() => {
    const dotLottieInstance = dotLottie();

    if (!dotLottieInstance) return;

    if (typeof config.renderConfig === 'object') {
      dotLottieInstance.setRenderConfig(config.renderConfig);
    }
  });
  // data
  createEffect(
    on(
      () => config.data,
      () => {
        const dotLottieInstance = dotLottie();

        if (!dotLottieInstance) return;

        if (typeof config.data === 'string') {
          dotLottieInstance.load({
            data: config.data,
            ...config,
          });
        }
      },
    ),
  );
  // src
  createEffect(
    on(
      () => config.src,
      () => {
        const dotLottieInstance = dotLottie();

        if (!dotLottieInstance) return;

        if (typeof config.src === 'string') {
          dotLottieInstance.load({
            src: config.src,
            ...config,
          });
        }
      },
    ),
  );
  // marker
  createEffect(() => {
    const dotLottieInstance = dotLottie();

    if (!dotLottieInstance) return;

    if (typeof config.marker === 'string') {
      dotLottieInstance.setMarker(config.marker);
    }
  });
  // resizeObserver
  createEffect(() => {
    if (!resizeObserver()) return;

    if (config.autoResizeCanvas && canvasRef) {
      resizeObserver()?.observe(canvasRef);
    } else {
      resizeObserver()?.disconnect();
    }
  });

  // animationId reactivity
  createEffect(
    on(
      () => config.animationId,
      () => {
        const dotLottieInstance = dotLottie();

        if (!dotLottieInstance) return;

        if (
          dotLottieInstance.isLoaded &&
          config.animationId &&
          dotLottieInstance.activeAnimationId !== config.animationId
        ) {
          dotLottieInstance.loadAnimation(config.animationId);
        }
      },
    ),
  );

  // themeId reactivity
  createEffect(
    on(
      () => config.themeId,
      () => {
        const dotLottieInstance = dotLottie();

        if (!dotLottieInstance) return;

        if (dotLottieInstance.isLoaded && dotLottieInstance.activeThemeId !== config.themeId) {
          dotLottieInstance.loadTheme(config.themeId || '');
        }
      },
    ),
  );

  // themeData reactivity
  createEffect(
    on(
      () => config.themeData,
      () => {
        const dotLottieInstance = dotLottie();

        if (!dotLottieInstance) return;

        if (dotLottieInstance.isLoaded) {
          dotLottieInstance.loadThemeData(config.themeData || '');
        }
      },
    ),
  );

  return {
    dotLottie,
    setCanvasRef,
    setContainerRef,
    canvas: canvasRef,
    container: containerRef,
    DotLottieComponent: Component,
  };
};

export const setWasmUrl = (url: string): void => {
  DotLottie.setWasmUrl(url);
};

// packages/react/src/use-dotlottie.tsx
import type { Config } from '@lottiefiles/dotlottie-web';
import { DotLottie } from '@lottiefiles/dotlottie-web';
import debounce from 'debounce';
import React, { useCallback, useState, useMemo, useEffect, useRef } from 'react';
import type { ComponentProps, RefCallback } from 'react';

interface DotLottieComponentProps {
  setCanvasRef: RefCallback<HTMLCanvasElement>;
  setContainerRef: RefCallback<HTMLElement>;
}

function DotLottieComponent({
  children,
  className = '',
  setCanvasRef,
  setContainerRef,
  style,
  ...rest
}: DotLottieComponentProps & ComponentProps<'canvas'>): JSX.Element {
  const containerStyle = {
    width: '100%',
    height: '100%',
    lineHeight: 0,
    ...style,
  };

  return (
    <div ref={setContainerRef} className={className} {...(!className && { style: containerStyle })}>
      <canvas
        ref={setCanvasRef}
        style={{
          width: '100%',
          height: '100%',
        }}
        {...rest}
      >
        {children}
      </canvas>
    </div>
  );
}

export type DotLottieConfig = Omit<Config, 'canvas'> & {
  animationId?: string;
  autoResizeCanvas?: boolean;
  playOnHover?: boolean;
  themeData?: string;
  themeId?: string;
};

export interface UseDotLottieResult {
  DotLottieComponent: (props: ComponentProps<'canvas'>) => JSX.Element;
  canvas: HTMLCanvasElement | null;
  container: HTMLDivElement | null;
  dotLottie: DotLottie | null;
  setCanvasRef: RefCallback<HTMLCanvasElement>;
  setContainerRef: RefCallback<HTMLDivElement>;
}

const isServerSide = (): boolean => typeof window === 'undefined';

export const useDotLottie = (config?: DotLottieConfig): UseDotLottieResult => {
  const [dotLottie, setDotLottie] = useState<DotLottie | null>(null);

  const dotLottieRef = useRef<DotLottie | null>(null);
  const configRef = useRef<DotLottieConfig | undefined>(config);

  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const containerRef = useRef<HTMLDivElement | null>(null);

  dotLottieRef.current = dotLottie;
  configRef.current = config;

  const hoverHandler = useCallback((event: MouseEvent) => {
    if (!configRef.current?.playOnHover || !dotLottieRef.current?.isLoaded) return;

    if (event.type === 'mouseenter') {
      dotLottieRef.current.play();
    } else if (event.type === 'mouseleave') {
      dotLottieRef.current.pause();
    }
  }, []);

  const intersectionObserver = useMemo(() => {
    if (isServerSide()) return null;

    const observerCallback = (entries: IntersectionObserverEntry[]): void => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          dotLottieRef.current?.unfreeze();
        } else {
          dotLottieRef.current?.freeze();
        }
      });
    };

    return new IntersectionObserver(observerCallback, {
      threshold: 0,
    });
  }, []);

  const resizeObserver = useMemo(() => {
    if (isServerSide()) return null;

    const observerCallback = debounce(() => {
      if (configRef.current?.autoResizeCanvas) {
        dotLottieRef.current?.resize();
      }
    }, 150);

    return new ResizeObserver(observerCallback);
  }, []);

  const setCanvasRef = useCallback((canvas: HTMLCanvasElement | null) => {
    canvasRef.current = canvas;
  }, []);

  const setContainerRef = useCallback((container: HTMLDivElement | null) => {
    containerRef.current = container;
  }, []);

  const Component = useCallback(
    (props: ComponentProps<'canvas'>): JSX.Element => {
      return <DotLottieComponent setContainerRef={setContainerRef} setCanvasRef={setCanvasRef} {...props} />;
    },
    [setCanvasRef, setContainerRef],
  );

  useEffect(() => {
    const canvas = canvasRef.current;

    let dotLottieInstance: DotLottie | null = null;

    if (canvas) {
      dotLottieInstance = new DotLottie({
        ...configRef.current,
        canvas,
      });

      // Check if the canvas is initially in view
      const initialEntry = canvas.getBoundingClientRect();

      if (
        initialEntry.top >= 0 &&
        initialEntry.left >= 0 &&
        initialEntry.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
        initialEntry.right <= (window.innerWidth || document.documentElement.clientWidth)
      ) {
        dotLottieInstance.unfreeze();
      } else {
        dotLottieInstance.freeze();
      }

      intersectionObserver?.observe(canvas);

      if (config?.autoResizeCanvas) {
        resizeObserver?.observe(canvas);
      }
      canvas.addEventListener('mouseenter', hoverHandler);
      canvas.addEventListener('mouseleave', hoverHandler);

      setDotLottie(dotLottieInstance);
    }

    return () => {
      dotLottieInstance?.destroy();
      setDotLottie(null);
      resizeObserver?.disconnect();
      intersectionObserver?.disconnect();
      canvas?.removeEventListener('mouseenter', hoverHandler);
      canvas?.removeEventListener('mouseleave', hoverHandler);
    };
  }, [intersectionObserver, resizeObserver, hoverHandler]);

  // speed reactivity
  useEffect(() => {
    if (!dotLottieRef.current) return;

    if (typeof config?.speed === 'number' && config.speed !== dotLottieRef.current.speed) {
      dotLottieRef.current.setSpeed(config.speed);
    }
  }, [config?.speed]);

  // mode reactivity
  useEffect(() => {
    if (!dotLottieRef.current) return;

    if (typeof config?.mode === 'string' && config.mode !== dotLottieRef.current.mode) {
      dotLottieRef.current.setMode(config.mode);
    }
  }, [config?.mode]);

  // loop reactivity
  useEffect(() => {
    if (!dotLottieRef.current) return;

    if (typeof config?.loop === 'boolean' && config.loop !== dotLottieRef.current.loop) {
      dotLottieRef.current.setLoop(config.loop);
    }
  }, [config?.loop]);

  // useFrameInterpolation reactivity
  useEffect(() => {
    if (!dotLottieRef.current) return;

    if (
      typeof config?.useFrameInterpolation === 'boolean' &&
      config.useFrameInterpolation !== dotLottieRef.current.useFrameInterpolation
    ) {
      dotLottieRef.current.setUseFrameInterpolation(config.useFrameInterpolation);
    }
  }, [config?.useFrameInterpolation]);

  // segment reactivity
  useEffect(() => {
    if (!dotLottieRef.current) return;

    if (
      typeof config?.segment === 'object' &&
      Array.isArray(config.segment) &&
      // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
      config.segment.length === 2
    ) {
      const startFrame = config.segment[0];
      const endFrame = config.segment[1];

      dotLottieRef.current.setSegment(startFrame, endFrame);
    }
  }, [config?.segment]);

  // background color reactivity
  useEffect(() => {
    if (!dotLottieRef.current) return;

    if (
      typeof config?.backgroundColor === 'string' &&
      config.backgroundColor !== dotLottieRef.current.backgroundColor
    ) {
      dotLottieRef.current.setBackgroundColor(config.backgroundColor);
    }
  }, [config?.backgroundColor]);

  // render config reactivity
  useEffect(() => {
    if (!dotLottieRef.current) return;

    if (typeof config?.renderConfig === 'object') {
      dotLottieRef.current.setRenderConfig(config.renderConfig);
    }
  }, [JSON.stringify(config?.renderConfig)]);

  // data reactivity
  useEffect(() => {
    if (!dotLottieRef.current) return;

    if (typeof config?.data === 'string' || config?.data instanceof ArrayBuffer) {
      dotLottieRef.current.load({
        data: config.data,
        ...(configRef.current || {}),
      });
    }
  }, [config?.data]);

  // src reactivity
  useEffect(() => {
    if (!dotLottieRef.current) return;

    if (typeof config?.src === 'string') {
      dotLottieRef.current.load({
        src: config.src,
        ...(configRef.current || {}),
      });
    }
  }, [config?.src]);

  useEffect(() => {
    if (!dotLottieRef.current) return;

    if (typeof config?.marker === 'string') {
      dotLottieRef.current.setMarker(config.marker);
    }
  }, [config?.marker]);

  useEffect(() => {
    if (!resizeObserver) return;

    if (config?.autoResizeCanvas && canvasRef.current) {
      resizeObserver.observe(canvasRef.current);
    } else {
      resizeObserver.disconnect();
    }
  }, [config?.autoResizeCanvas, resizeObserver]);

  // animationId reactivity
  useEffect(() => {
    if (!dotLottieRef.current) return;

    if (
      dotLottieRef.current.isLoaded &&
      config?.animationId &&
      dotLottieRef.current.activeAnimationId !== config.animationId
    ) {
      dotLottieRef.current.loadAnimation(config.animationId);
    }
  }, [config?.animationId]);

  // themeId reactivity
  useEffect(() => {
    if (!dotLottieRef.current) return;

    if (dotLottieRef.current.isLoaded && dotLottieRef.current.activeThemeId !== config?.themeId) {
      dotLottieRef.current.loadTheme(config?.themeId || '');
    }
  }, [config?.themeId]);

  // themeData reactivity
  useEffect(() => {
    if (!dotLottieRef.current) return;

    if (dotLottieRef.current.isLoaded) {
      dotLottieRef.current.loadThemeData(config?.themeData || '');
    }
  }, [config?.themeData]);

  return {
    dotLottie,
    setCanvasRef,
    setContainerRef,
    canvas: canvasRef.current,
    container: containerRef.current,
    DotLottieComponent: Component,
  };
};
