// packages/react/src/dotlottie.tsx
import type { DotLottie, Config } from '@lottiefiles/dotlottie-web';
import type { ComponentProps, RefCallback } from 'react';
import React from 'react';

import { useDotLottie } from './use-dotlottie';
import useStableCallback from './use-stable-callback';

export type DotLottieReactProps = Omit<Config, 'canvas'> &
  ComponentProps<'canvas'> & {
    autoResizeCanvas?: boolean;
    dotLottieRefCallback?: RefCallback<DotLottie>;
    playOnHover?: boolean;
  };

export const DotLottieReact = ({
  autoResizeCanvas = true,
  autoplay,
  backgroundColor,
  data,
  dotLottieRefCallback,
  loop,
  marker,
  mode,
  playOnHover,
  renderConfig,
  segment,
  speed,
  src,
  useFrameInterpolation,
  ...props
}: DotLottieReactProps): JSX.Element => {
  const { DotLottieComponent, dotLottie } = useDotLottie({
    data,
    mode,
    speed,
    src,
    autoplay,
    loop,
    segment,
    renderConfig,
    backgroundColor,
    useFrameInterpolation,
    playOnHover,
    autoResizeCanvas,
    marker,
  });

  const stableDotLottieRefCallback =
    typeof dotLottieRefCallback === 'function' ? useStableCallback(dotLottieRefCallback) : undefined;

  React.useEffect(() => {
    if (typeof stableDotLottieRefCallback === 'function') {
      stableDotLottieRefCallback(dotLottie);
    }
  }, [stableDotLottieRefCallback, dotLottie]);

  return <DotLottieComponent {...props} />;
};

// packages/solid/src/dotlottie.tsx
import type { Config, DotLottie } from '@lottiefiles/dotlottie-web';
import { ComponentProps, JSX, createEffect, splitProps } from 'solid-js';

import { useDotLottie } from './use-dotlottie';
import useStableCallback from './use-stable-callback';

export type DotLottieSolidProps = Omit<Config, 'canvas'> &
	ComponentProps<'canvas'> &
	Partial<{
		autoResizeCanvas: boolean;
		dotLottieRefCallback: (dotLottie: DotLottie) => void;
		playOnHover: boolean;
	}>;

export const DotLottieSolid = (props: DotLottieSolidProps): JSX.Element => {
	const [dotLottieProps, restProps] = splitProps(props, [
		'src',
		'data',
		'mode',
		'loop',
		'speed',
		'marker',
		'segment',
		'autoplay',
		'playOnHover',
		'renderConfig',
		'autoResizeCanvas',
		'dotLottieRefCallback',
		'useFrameInterpolation',
	]);
	const { DotLottieComponent, dotLottie } = useDotLottie(dotLottieProps);

	const stableDotLottieRefCallback =
		typeof dotLottieProps.dotLottieRefCallback === 'function'
			? useStableCallback(dotLottieProps.dotLottieRefCallback)
			: undefined;

	createEffect(() => {
		if (typeof stableDotLottieRefCallback === 'function') {
			stableDotLottieRefCallback(dotLottie()!);
		}
	});

	return <DotLottieComponent {...restProps} />;
};
