// apps/dotlottie-vue-example/src/App.vue
<script setup lang="ts">
import { Ref, onMounted, ref } from 'vue';
import { type DotLottieVueInstance, DotLottieVue, setWasmUrl } from '@lottiefiles/dotlottie-vue';
import wasmUrl from '../../../packages/web/src/core/dotlottie-player.wasm?url';

setWasmUrl(wasmUrl);

function dotLottieRefCallback(dotLottie: DotLottieVueInstance) {
  console.log('dotLottieRefCallback', dotLottie);
}

const player: Ref<DotLottieVueInstance | null> = ref(null);

function toggleLoop() {
  const dotLottie = player.value?.getDotLottieInstance();
  dotLottie?.setLoop(!dotLottie?.loop);
}

function play() {
  player.value?.getDotLottieInstance()?.play();
}
function pause() {
  player.value?.getDotLottieInstance()?.pause();
}
function stop() {
  player.value?.getDotLottieInstance()?.stop();
}

onMounted(() => {
  if (player.value) {
    const dotLottie = player.value?.getDotLottieInstance();
    dotLottie?.addEventListener('play', () => {
      console.log('play');
    });
    dotLottie?.addEventListener('stop', () => {
      console.log('stop');
    });
    dotLottie?.addEventListener('pause', () => {
      console.log('paused');
    });
    // dotLottie.addEventListener('frame', ({currentFrame}) => {
    //   console.log('Frame:', currentFrame)
    // });
    dotLottie?.addEventListener('complete', () => {
      console.log('completed');
    });
  }
});
</script>

<template>
  <DotLottieVue
    background-color="#222"
    style="height: 500px; width: 500px"
    autoplay
    loop
    ref="player"
    src="https://lottie.host/5525262b-4e57-4f0a-8103-cfdaa7c8969e/VCYIkooYX8.json"
    :dot-lottie-ref-callback="dotLottieRefCallback"
    play-on-hover
  />
  <div class="btn-group">
    <button @click="toggleLoop">Toggle Loop</button>
    <button @click="stop">Stop</button>
    <button @click="pause">Pause</button>
    <button @click="play">Play</button>
  </div>
</template>

<style scoped>
.btn-group {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
  gap: 0.5rem;
}
</style>

// apps/dotlottie-solid-example/src/App.tsx
import { type DotLottie, DotLottieSolid, setWasmUrl } from '@lottiefiles/dotlottie-solid';
import type { Component } from 'solid-js';
import { createEffect, createSignal } from 'solid-js';

import wasmUrl from '../../../packages/web/src/core/dotlottie-player.wasm?url';

const animations = [
  // eslint-disable-next-line no-secrets/no-secrets
  'https://lottie.host/647eb023-6040-4b60-a275-e2546994dd7f/zDCfp5lhLe.json',
  // eslint-disable-next-line no-secrets/no-secrets
  'https://lottie.host/f315768c-a29b-41fd-b5a8-a1c1dfb36cd2/CRiiNg8fqQ.lottie',
];

setWasmUrl(wasmUrl);

const App: Component = () => {
  const [dotLottie, setDotlottie] = createSignal<DotLottie>();
  const [loop, setLoop] = createSignal(true);
  const [speed, setSpeed] = createSignal(1);
  const [srcIdx, setSrcIdx] = createSignal(0);
  const [useFrameInterpolation, setUseFrameInterpolation] = createSignal(false);
  const [playOnHover, setPlayOnHover] = createSignal(false);
  const [autoResizeCanvas, setAutoResizeCanvas] = createSignal(true);

  function play(): void {
    dotLottie()?.play();
  }

  function pause(): void {
    dotLottie()?.pause();
  }

  function stop(): void {
    dotLottie()?.stop();
  }

  function handleLoop(): void {
    setLoop((prev) => !prev);
  }

  function increaseSpeed(): void {
    setSpeed((prev) => prev + 0.1);
  }

  function decreaseSpeed(): void {
    setSpeed((prev) => prev - 0.1);
  }

  function changeSrc(): void {
    const totalAnimations = animations.length;
    const nextSrcIdx = (srcIdx() + 1) % totalAnimations;

    setSrcIdx(nextSrcIdx);
  }

  function handleUseFrameInterpolation(): void {
    setUseFrameInterpolation((prev) => !prev);
  }

  function handlePlayOnHover(): void {
    setPlayOnHover((prev) => !prev);
  }

  function handleAutoResizeCanvas(): void {
    setAutoResizeCanvas((prev) => !prev);
  }

  createEffect(() => {
    const dotLottieInstance = dotLottie();

    if (dotLottieInstance) {
      dotLottieInstance.addEventListener('play', console.log);
      dotLottieInstance.addEventListener('pause', console.log);
      dotLottieInstance.addEventListener('stop', console.log);
    }
  });

  return (
    <div
      style={{
        display: 'flex',
        'flex-direction': 'column',
        'align-items': 'center',
        gap: '10px',
      }}
    >
      <DotLottieSolid
        dotLottieRefCallback={setDotlottie}
        useFrameInterpolation={useFrameInterpolation()}
        src={animations[srcIdx()]}
        autoplay
        loop={loop()}
        speed={speed()}
        playOnHover={playOnHover()}
        autoResizeCanvas={autoResizeCanvas()}
        style={{
          height: '500px',
        }}
      />
      <div
        style={{
          display: 'flex',
          gap: '10px',
        }}
      >
        <button onClick={play}>Play</button>
        <button onClick={pause}>Pause</button>
        <button onClick={stop}>Stop</button>
        <button onClick={handleLoop}>{loop() ? 'Looping' : 'Not looping'}</button>
        <button onClick={increaseSpeed}>+ Speed</button>
        <button onClick={decreaseSpeed}>- Speed</button>
        <button onClick={changeSrc}>Change src</button>
        <button onClick={handleUseFrameInterpolation}>
          {useFrameInterpolation() ? 'Using frame interpolation' : 'Not using frame interpolation'}
        </button>
        <button onClick={handlePlayOnHover}>{playOnHover() ? 'Play on hover' : 'Not play on hover'}</button>
        <label>
          <input type="checkbox" checked={autoResizeCanvas()} onChange={handleAutoResizeCanvas} />
          Auto Resize
        </label>
      </div>
    </div>
  );
};

export default App;
